Make sure scripts fail on first failure
For example, in `build-dockerimage.sh`, it doesn't make sense to build
the image if cloning has failed, which is surprisingly often now:

```
Cloning into 'rockbox-git/rockbox'...
remote: Enumerating objects: 10569, done.
remote: Counting objects: 100% (10569/10569), done.
remote: Compressing objects: 100% (9328/9328), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 3046 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```